# Record which repository this firmware is being built from, and whether the
# source tree has uncommitted changes.
#
# Run as a build step rather than at CMake configure time, because the answer
# changes without any file CMake watches changing: edit a source file after a
# clean build and the tree is dirty, but CMakeLists.txt is untouched, so a
# configure-time computation would keep reporting the old value. That is the
# common case, and it is exactly the one the guard exists for.
#
# Writes OUT only when the content differs, so an unchanged answer does not
# touch the header and does not trigger a rebuild.
#
#     cmake -DSRC=<source dir> -DOUT=<header path> -P gen_build_info.cmake

execute_process(
    COMMAND git config --get remote.origin.url
    WORKING_DIRECTORY "${SRC}"
    OUTPUT_VARIABLE ORIGIN
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)

execute_process(
    COMMAND git status --porcelain
    WORKING_DIRECTORY "${SRC}"
    OUTPUT_VARIABLE STATUS
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)

if(STATUS)
    set(DIRTY 1)
else()
    set(DIRTY 0)
endif()

# Strip anything that would break a C string literal. A remote URL should not
# contain these, but a build must not fail on a strange one either.
string(REGEX REPLACE "[^A-Za-z0-9:/._@-]" "" ORIGIN "${ORIGIN}")

set(NEW "/* Generated by tools/gen_build_info.cmake. Do not edit. */
#ifndef FW_BUILD_INFO_H
#define FW_BUILD_INFO_H
/* The repository this firmware was built from, and whether the tree had local
   changes. fw_update.c uses both to refuse a feed that is not this build's own
   repository, so a fork or a local edit is not silently replaced. */
#define FW_BUILD_REPO \"${ORIGIN}\"
#define FW_BUILD_DIRTY ${DIRTY}
#endif
")

if(EXISTS "${OUT}")
    file(READ "${OUT}" OLD)
else()
    set(OLD "")
endif()

if(NOT OLD STREQUAL NEW)
    file(WRITE "${OUT}" "${NEW}")
    message(STATUS "EmbedWRT provenance: origin='${ORIGIN}' dirty=${DIRTY}")
else()
    message(STATUS "EmbedWRT provenance: unchanged (origin='${ORIGIN}' dirty=${DIRTY})")
endif()
